#######äëÿ Fly Elephant######
install.packages('sp', repos='http://cran.us.r-project.org', lib= "~/")
install.packages('ade4', repos='http://cran.us.r-project.org', lib= "~/")
install.packages('adehabitatMA', repos='http://cran.us.r-project.org', lib= "~/")
install.packages('CircStats', repos='http://cran.us.r-project.org', lib= "~/")
install.packages('deldir', repos='http://cran.us.r-project.org', lib= "~/")
install.packages('adehabitatHR', repos='http://cran.us.r-project.org', lib= "~/")
install.packages('adehabitatLT', repos='http://cran.us.r-project.org', lib= "~/")
library("sp",lib.loc = "~/")
library("ade4",lib.loc = "~/")
library("adehabitatMA",lib.loc = "~/")
library("CircStats",lib.loc = "~/")
library("deldir",lib.loc = "~/")
library("adehabitatLT",lib.loc = "~/")
library("adehabitatHR",lib.loc = "~/")
print('start')
data<-dget(file='~/workdir/data_after_cleaning')
print('a1')
data_res<-data[!data$far_trip&data$zero_delete!='delete',]
print('a2')
data.traj<-with(data_res, 
                as.ltraj(xy = data.frame(x=Re(z_adj),y=Im(z_adj)), date = date_time,id=ID))
print('a3')
kernel_Brownian<-kernelbb(data.traj, sig1=0.5, sig2=15, grid = 900, same4all = TRUE, 
                          byburst = TRUE,extent = 0.1, nalpha = 25)
print('a4')
save(kernel_Brownian,file='~/workdir/kernel_Brownian')
