#######äëÿ Fly Elephant######
install.packages('sp', repos='http://cran.us.r-project.org', lib= "~/")
install.packages('ade4', repos='http://cran.us.r-project.org', lib= "~/")
install.packages('adehabitatMA', repos='http://cran.us.r-project.org', lib= "~/")
install.packages('CircStats', repos='http://cran.us.r-project.org', lib= "~/")
install.packages('deldir', repos='http://cran.us.r-project.org', lib= "~/")
install.packages('adehabitatHR', repos='http://cran.us.r-project.org', lib= "~/")
install.packages('adehabitatLT', repos='http://cran.us.r-project.org', lib= "~/")
library("sp",lib.loc = "~/")
library("ade4",lib.loc = "~/")
library("adehabitatMA",lib.loc = "~/")
library("CircStats",lib.loc = "~/")
library("deldir",lib.loc = "~/")
library("adehabitatLT",lib.loc = "~/")
library("adehabitatHR",lib.loc = "~/")
print('start')
load(file='data_traj')
print('a1')
kernel_Brownian<-kernelbb(data.traj, sig1=0.5, sig2=15, grid = 900, same4all = TRUE, 
                              byburst = TRUE,extent = 0.1, nalpha = 25)
print('a2')
save(kernel_Brownian,file='kernel_Brownian')
